### ISSUE TITLE
please delete

### ISSUE THREAD

**Issue by schumiel** [georgringer/noopener#7]
please delete

**Comment by BastianBalthasarBux** [comment]
Your message is more than offensive, maybe you should rethink your attitude. If I was Georg, I would now be really unmotivated and just stop my free work on that, and maybe even hide the repo from the public.

To the question, it's pretty easy to answer.

1. If one writes HTML in a template, we should be allowed to expect this one has got more brain than 2m of a country lane. Thus we could expect, this one writes the rel attribute correctly and savely in exactly the way it should appear.

2. Nevertheless what you want could have been done, but in a completely different way. Georg hooked into the ContentObjectRenderer. That means, the rel-attribute gets added with some sanitation logic on a relatively early stage of generating the page.
What you want, would mean to reparse the whole page after it got created, like e.g. extension sourceopt does. This has several significant disadvantages in this case, e.g. you would need maybe a regex to find URLs (which is also error-prone), you must completely test them on your own if they are internally/externally, relative etc... 
This would also be pretty in-performant and would need a full bloated bunch of code. All for the sake, that some moron who thinks to be able to write correct HTML is not aware that he/she is not.

**Comment by schumiel** [comment]
Wow, no. My questions were not intended to attack Georg. I just wanted to know why and why. Just to know how complex this would be. Not in the beginning I wanted something bad with my questions. I apologize if this has been interpreted in this way. But it wasn't in my interest.

Please close / delete thread.
