### ISSUE TITLE
Requiring package with dev-master#<sha1> not possible

### ISSUE THREAD

**Issue by josefglatz** [georgringer/noopener#8]
I can't find the reason for, but the detail page on packagist.org https://packagist.org/packages/georgringer/noopener doesn't show dev-master in the list above version tags. This is shown for other packages like news or my packages. Seems like this has something todo with the composer.json? Can't find the problem just by reading.

**Comment by georgringer** [comment]
there have been warnings at `composer.json` which I fixed just now. please test again with version 1.0.1
